---
title: "DSAC Analysis"
format: html
editor: visual
---

```{r 9, warning=FALSE, message=FALSE}
library(readr)
library(tidyverse)
library(tidymodels)
library(ggplot2)
library(corrplot)
```

```{r 10, warning=FALSE, message=FALSE}
combine_results <- read_csv("combine_results.csv")
receiving<- read_csv("Career_Stats_Receiving.csv")
```

### Creating One Single Dataset

```{r 12}

# Filter receiving data frame for Year >= 1987
receiving <- subset(receiving, Year >= 1987)

# Reverse the order of names in the 'Name' column
receiving$Name <- sapply(strsplit(receiving$Name, ", "), function(x) paste(rev(x), collapse = " "))

# Make common player names in both datasets
combine_results <- combine_results %>%
  mutate(name=tolower(name))

receiving <- receiving %>%
  mutate(Name=tolower(Name))

# Merge the data frames
merged_data_receiving <- merge(combine_results, receiving, by.x = "name", by.y = "Name", all = TRUE)

# Remove Duplicate Players
merged_data_receiving <- merged_data_receiving %>% 
  distinct()

# Remove the 'pos' and 'Player Id' columns from merged_data_receiving
merged_data_receiving <- merged_data_receiving[, !(names(merged_data_receiving) %in% c("pos", "Player Id"))]
```

```{r 13}
view(merged_data_receiving)
```

### Correlation Heatmats

```{r 1, message = F, warning = F}
selected_variables <- merged_data_receiving[, c("height_in", "weight_lbs", "hand_size_in", 
                                      "40_yard", "bench_press", "vert_leap_in", 
                                      "broad_jump_in", "shuttle", "3cone", 
                                      "Receptions", "Receiving Yards", 
                                      "Yards Per Reception", "Receiving TDs", 
                                      "First Down Receptions")]

selected_variables <- as.data.frame(sapply(selected_variables, function(x) as.numeric(as.character(x))))

# Calculate the correlation matrix
correlation_matrix <- cor(selected_variables, use = "pairwise.complete.obs")

# Create a correlation heatmap
corrplot(correlation_matrix, method = "color", type = "upper", tl.col = "black", tl.srt = 45)
```

Upon inspection of this correlation heatmap, there appears to be little correlation between the NFL combine stats and receiver stats for any combination.

### Scatterplots

```{r 2, message = F, warning = F}
ggplot(merged_data_receiving, aes(x = `40_yard`, y = `Receiving Yards`)) +
  geom_point() +
  labs(x = "40 Yard", y = "Receiving Yards", 
       title = "Scatterplot between 40 Yard and Receiving Yards")
```

No relationship is evident

```{r 3, message = F, warning = F}
ggplot(merged_data_receiving, aes(x = `40_yard`, y = `Yards Per Reception`)) +
  geom_point() +
  labs(x = "40 Yard", y = "Yards Per Reception", 
       title = "Scatterplot between 40 Yard and Yards Per Reception")
```

No relationship is evident.
